version: '3.8'

services:
  webcrawler:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    container_name: webcrawler
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - webcrawler
